# Generated by Django 4.1.5 on 2023-01-22 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HellowWorld',
            new_name='HelloWorld',
        ),
    ]
