# Generated by Django 4.1.5 on 2023-01-28 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0002_rename_hellowworld_helloworld'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HelloWorld',
        ),
    ]
