# Generated by Django 4.1.5 on 2023-01-26 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='write',
            new_name='writer',
        ),
    ]
